In [1]:
#starting a sentimental analysis project , data set is downloaded from kaggle 

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('movie.csv')

In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [6]:
df.shape

(50000, 2)

In [7]:
df['review'].value_counts()

review
Loved today's show!!! It was a variety and not solely cooking (which would have been great too). Very stimulating and captivating, always keeping the viewer peeking around the corner to see what was coming up next. She is as down to earth and as personable as you get, like one of us which made the show all the more enjoyable. Special guests, who are friends as well made for a nice surprise too. Loved the 'first' theme and that the audience was invited to play along too. I must admit I was shocked to see her come in under her time limits on a few things, but she did it and by golly I'll be writing those recipes down. Saving time in the kitchen means more time with family. Those who haven't tuned in yet, find out what channel and the time, I assure you that you won't be disappointed.                                                                                                                                                                                                         

In [8]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [9]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
#there is no null value in the dataset

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import string


In [12]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [13]:
#neccessary libraries for preprocessing is imported
 

In [14]:
lemmatizer=WordNetLemmatizer()
stop_words=set(stopwords.words('english'))

In [15]:
def preprocess_text(text):
    # Lowercase
    text = text.lower()
    
    # Remove URLs, mentions, hashtags
    text = re.sub(r"http\S+|www\S+|@\w+|#\w+", "", text)
    
    # Remove punctuation and digits
    text = re.sub(r"[^\w\s]", "", text)  # remove punctuation
    text = re.sub(r"\d+", "", text)      # remove digits
    
    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    # Tokenize
    tokens = text.split()
    
    # Remove stopwords and lemmatize
    cleaned = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    
    return " ".join(cleaned)


In [16]:
df['cleaned'] = df['review'].apply(preprocess_text) 

# Display the DataFrame with the cleaned text
print(df)

                                                  review sentiment  \
0      One of the other reviewers has mentioned that ...  positive   
1      A wonderful little production. <br /><br />The...  positive   
2      I thought this was a wonderful way to spend ti...  positive   
3      Basically there's a family where a little boy ...  negative   
4      Petter Mattei's "Love in the Time of Money" is...  positive   
...                                                  ...       ...   
49995  I thought this movie did a down right good job...  positive   
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative   
49997  I am a Catholic taught in parochial elementary...  negative   
49998  I'm going to have to disagree with the previou...  negative   
49999  No one expects the Star Trek movies to be high...  negative   

                                                 cleaned  
0      one reviewer mentioned watching oz episode you...  
1      wonderful little production br br 

In [17]:
# the above function cleans the words in the tweet column ,first lower the text then convert to each tokens , lemmatizer reduces to base form

In [18]:
df['cleaned']

0        one reviewer mentioned watching oz episode you...
1        wonderful little production br br filming tech...
2        thought wonderful way spend time hot summer we...
3        basically there family little boy jake think t...
4        petter matteis love time money visually stunni...
                               ...                        
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary school nu...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movie high art fan expec...
Name: cleaned, Length: 50000, dtype: object

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf=TfidfVectorizer(max_features=5000)
x=tfidf.fit_transform(df['cleaned']).toarray()

In [21]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
x.shape

(50000, 5000)

In [23]:
#some changes are done , y is not labeled 


In [24]:
y=df['sentiment']

In [25]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 50000, dtype: object

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y, random_state=42)

In [28]:
# encoded the sentiments, cleaned the input text , the data is split according the unique value of  y labels


In [29]:
x_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.23160884,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
from sklearn.linear_model import LogisticRegression


In [31]:
model=LogisticRegression(solver='saga',max_iter=100)

In [32]:
model.fit(x_train,y_train)

LogisticRegression(solver='saga')

In [33]:
y_pred=model.predict(x_test)

In [34]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [35]:
print('accuracy:',accuracy_score(y_test,y_pred))

accuracy: 0.8862


In [36]:
print('\nclassification report;\n',classification_report(y_test,y_pred))


classification report;
               precision    recall  f1-score   support

    negative       0.90      0.87      0.88      5000
    positive       0.88      0.90      0.89      5000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [37]:
print('\nconfusion matrix:\n',confusion_matrix(y_test,y_pred))


confusion matrix:
 [[4372  628]
 [ 510 4490]]


In [38]:
import pickle

In [39]:
with open('model/sentiment_model.pkl','wb') as f:
    pickle.dump(model,f)

In [40]:
with open('model/tfidf.pkl','wb') as f:
    pickle.dump(tfidf,f)

In [41]:
g='good movie'

In [42]:
preprocess_text(g)

'good movie'

In [43]:
tfidf.transform([preprocess_text(g)])

<1x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [44]:
tfidf.transform([preprocess_text(g)]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [45]:
model.predict(tfidf.transform([preprocess_text(g)]).toarray())

array(['positive'], dtype=object)

In [46]:
# the prediction is positive for  comment ; good movie 

In [47]:
d='bad experience'

In [48]:
model.predict(tfidf.transform([preprocess_text(d)]).toarray())

array(['negative'], dtype=object)

In [49]:
# the prediction is negative for the comment bad experience

next training in svm

In [50]:
from sklearn.svm import LinearSVC
model2 = LinearSVC()
model2.fit(x_train, y_train)


LinearSVC()

In [51]:
y_pred=model2.predict(x_test)

In [52]:
print('accuracy:',accuracy_score(y_test,y_pred))

accuracy: 0.8805


In [53]:
print('\nclassification report;\n',classification_report(y_test,y_pred))


classification report;
               precision    recall  f1-score   support

    negative       0.89      0.87      0.88      5000
    positive       0.88      0.89      0.88      5000

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



In [54]:
model2.predict(tfidf.transform([preprocess_text(g)]).toarray())

array(['positive'], dtype=object)

In [55]:
model2.predict(tfidf.transform([preprocess_text(d)]).toarray())

array(['negative'], dtype=object)